### ISSUE TITLE
Esc makes some games impossible to play

### ISSUE THREAD

**Issue by takov751** [hmlendea/geforcenow-electron#10]
Some games require usage of ESC on places where just impossible to avoid. For example in Argo and Hitman. Is there a way to remap it for a different key like scroll lock? Great ,straightforward project

**Comment by aintitfun** [comment]
+1 Anyway good project!

**Comment by hmlendea** [comment]
This is a nasty bug that so far I haven't found a solution for, as I was unable to replicate it consistently.
Furthermore, I am using the free tier, and waiting in queue for 30 minutes or more for each debug slows things down a lot :(

**Comment by hmlendea** [comment]
#12 also mentions this same issue

**Comment by takov751** [comment]
Perfectly reasonable. I have rolled back to the previous release . Sadly I have not much time to experiment,hopefully I will come back to you in the next few days

**Comment by takov751** [comment]
I had the idea to use this section https://www.electronjs.org/docs/tutorial/keyboard-shortcuts

where you could remap a key/keycombination hidden as platform specific variable 
```
{
  accelerator: process.platform === 'darwin' ? 'Alt+Cmd+I' : 'Ctrl+Shift+I'
}

```
what do you think?

**Comment by eranok** [comment]
#15 Fix, merge soon
