### ISSUE TITLE
ESC key not working since last commit

### ISSUE THREAD

**Issue by Samy-ib** [hmlendea/geforcenow-electron#12]
Hi,
Before, it was exiting the full-screen mode and now it simply doesn't do anything (I use Manjaro with KDE). 
I don't know much about electron but it will be nice if there is an option to only exit the full-screen if you hold ESC key, just like in chromium(the browser).
Thanks.

**Comment by hmlendea** [comment]
Thanks for the report

As this was already raised in #10, I will close this issue so that the conversations can continue there for better visibility.
