### ISSUE TITLE
Full Screen Glitching

### ISSUE THREAD

**Issue by dzlandis** [hmlendea/geforcenow-electron#25]
The full screen mechanics for this app seem to be really weird. It isn't clear how to easily get in and out of full screen on Ubuntu 20.04.1 LTS and pressing escape doesn't work. Sometimes, the cursor can be trapped inside a small box of the window without an easy way to get out. The solution for this I have been using for now is opening a terminal with Control + T but this is a really bad solution. Perhaps I am missing something? Please let me know if you have any other questions as I am happy to provide more information.

**Comment by hmlendea** [comment]
I am going to change the fullscreen key combination soon and hopefully it will fix the issue.
I don't have Ubuntu to try it on but I will try to set up a VM with it.
