### ISSUE TITLE
Purple tint problem

### ISSUE THREAD

**Issue by JovanPetkovic** [hmlendea/geforcenow-electron#27]
Whenever I play a game every blue color goes to purple, and it is pretty annoying. I looked online for a solution, first I though it was my theme and other stuff. Through a lot of trial and error I found out that it is a chrome bug, here is the link to the bug.

https://geeksocket.in/blog/weird-color-chrome/#:~:text=Visit%20chrome%3A%2F%2Fflags%2F%23,rendering%20to%20Disable%20from%20Default.&text=Chromium%20also%20has%20this%20issue

**Comment by hmlendea** [comment]
Did anyone else experience this issue?
Is this still a problem for anyone?
