### ISSUE TITLE
ESC key should not be a un-fullscreen shortcut, it should be something else, or alt-tab only

### ISSUE THREAD

**Issue by goofyseeker311** [hmlendea/geforcenow-electron#33]
i dont wish my recordings to be messed by resizing of the screen, when not wanted, but moving in the game menus

**Comment by hmlendea** [comment]
Hello,

Are you using the latest version?

**Comment by goofyseeker311** [comment]
i deleted the whole operating system, but the latest snap what was in the store

**Comment by hmlendea** [comment]
Yeah... the version on the snap store is a bit outdated :(
The ESC key issue was addressed since that version

**Comment by hmlendea** [comment]
Closing this as so far it cannot be reproduced on the latest version
