### ISSUE TITLE
Video lag

### ISSUE THREAD

**Issue by Svampebob1** [hmlendea/geforcenow-electron#34]
Hi,

How are Geforce Now working for you and what kind of GPU are you using?

I'm experiencing big problems with lag. I had the same problem with Google Stadia. 
After installing non-free Intel i965 drivers and configuring Google Chrome with experimental GPU-support, then Google Stadia worked flawlessly. Geforce Now does not :-(.

Geforce Now runs better in Google Chrome for me, but still not good enough.
Could this be a driver issue?

Any tip that might lead me into fixing this will be highly appreciated.

Thanks.

**Comment by hmlendea** [comment]
Hmmm, I'm not sure what could cause the issue.

My setup is a very old 2012 laptop with GeForce 610M and the `nvidia-390xx` legacy drivers

**Comment by Svampebob1** [comment]
Funny thing is that, when rebooting, the problem gets much better!

I get the following messages in DMESG:
   60.020028] audit: type=1400 audit(1609933105.595:115): apparmor="DENIED" operation="open" profile="snap.geforcenow.geforcenow" name="/sys/bus/eisa/devices/" pid=5508 comm="ThreadPoolForeg" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0

**Comment by Svampebob1** [comment]
After further testing, I've found that when rebooting, the problem gets much better! Allmost perfectly!
The lag starts after playing for a few minutes.

I've changed from the non-free to the free drivers again.

There is no difference between these drivers.

I'll troubleshoot a bit more and share my findings with you.

I get the following messages in DMESG:
   60.020028] audit: type=1400 audit(1609933105.595:115): apparmor="DENIED" operation="open" profile="snap.geforcenow.geforcenow" name="/sys/bus/eisa/devices/" pid=5508 comm="ThreadPoolForeg" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0

**Comment by Svampebob1** [comment]
I switched to Wayland and played for about 20 minutes now.
This seems to fix the issue.

**Comment by hmlendea** [comment]
If you would still be willing to spend a bit more effort on this, can you try the non-snap version?

**Comment by Svampebob1** [comment]
I'll do some tests and come back to you.

**Comment by Svampebob1** [comment]
The non-snap version does not perform any better. I forgot to check DMESG when testing. I'll do that the next time.

**Comment by Svampebob1** [comment]
I have tested with the electron app now.
The video lag issue happens with Lutris Geforce Now browser app, Google Chrome and this app, until I restart my computer.
It's possible due to suspend, I think.
The problem starts after 5 minutes in Xorg. 

I have compared the performance in this app with the Geforce Now app in Windows set to competitive performance.
This app's performance is as good as the Windows Geforce Now app.

The Geforce Now Electron app also gets the error message in DMESG as mentioned above.

Do you want me to check the DMESG error by using the .DEB package instead?
