### ISSUE TITLE
Cannot seem to get microphone to connect

### ISSUE THREAD

**Issue by Angel-Tube** [hmlendea/geforcenow-electron#37]
Default chromium will prompt me but I cannot seem to speak input audio through this

**Comment by strexgth** [comment]
I seem to be having the same problem, and I am unsure on how to fix it!

**Comment by hmlendea** [comment]
Yes, I can also reproduce this issue.

I will take a look as soon as I can but I am a bit busy lately so it might take some time.

**Comment by strexgth** [comment]
Okay, thank you for this!

**Comment by hmlendea** [comment]
@strexgth @Angel-Tube Do you still have this problem?
It was fixed in the latest update.
