### ISSUE TITLE
Wayland?

### ISSUE THREAD

**Issue by strexgth** [hmlendea/geforcenow-electron#39]
Hi, I am using Linux Mint 20.1, and I have input delay/lag in Nvidia Geforce Now with Fortnite, and was told to switch to Wayland. I am still quite new to Linux, and I need help with this. Please help!

**Comment by 3nuc** [comment]
Is it ok to track Wayland support in this issue?

I'm getting this when trying to launch geforcenow-electron
```
git clone https://github.com/hmlendea/geforcenow-electron.git
cd geforcenow-electron
npx electron . --enable-logging
The futex facility returned an unexpected error code.
[homedir here]/dev/0gitmisc/geforcenow-electron/node_modules/electron/dist/electron exited with signal SIGABRT
```

Related resources:
https://wiki.archlinux.org/index.php/Wayland#Cannot_open_display:_:0_with_Electron-based_applications (tried this)

I'm not familiar with Electron but this issue https://github.com/electron/electron/issues/10915 seems to have been closed after v12 - geforcenow-electron uses v11. Would bumping the electron version help?

**Comment by hmlendea** [comment]
I'm unable to run Wayland on my current machine unfortunately, but the electron upgrade for this project will come today and we'll take it from there and see if it works.

**Comment by hmlendea** [comment]
I've released the new update which uses `electron v12.0.2`

**Comment by 3nuc** [comment]
It works on Wayland now! I just pulled your newest changes, ran npm install then ran npm start and it's starting. 

Thank you!

For context: Wayland 1.19.0-1

**Comment by strexgth** [comment]
@3nuc and @hmlendea I am unsure of what Wayland and "npm" is, and how to switch to it. Can someone please elaborate on this topic?

**Comment by hmlendea** [comment]
In very broad terms, Wayland is a display server that is used by your desktop environment (everything you see on the screen, the GUI of your PC, runs in a desktop environment).
There are two display servers on Linux: Wayland (newer, better, but still in development and not quite ready for mass adoption **yet**), and X11 (archaic, very bloated and slow, but it gets the job done and works for everyone).

npm is a package manager that you need to use if you want to manually compile this application.

**Comment by hmlendea** [comment]
Closing this as it was fixed in the latest update.

If issues occur again, it can be reopened or a new issue can be created.
