### ISSUE TITLE
Stuck on membership screen

### ISSUE THREAD

**Issue by jacobgonzales20** [hmlendea/geforcenow-electron#4]
So i logged into my account and got a free membership and it's stuck on that screen.

**Comment by hmlendea** [comment]
What exactly means stuck? You cannot select items?
Are you refering to the game selection screen?

**Comment by jacobgonzales20** [comment]
> What exactly means stuck? You cannot select items?
> Are you refering to the game selection screen?

referring to game selection screen it doesn't pop up, i'm stuck on picking a plan for geforce now.

**Comment by hmlendea** [comment]
Could you try deleting this directory? `~/.config/GeForce Now`

**Comment by hmlendea** [comment]
Closing as this should have been closed by #5
