### ISSUE TITLE
Unable To Authenticate Using Google On Linux

### ISSUE THREAD

**Issue by InfoSec812** [hmlendea/geforcenow-electron#40]
When I try to use Google Social login I get a message when I try to log in to Google that my browser is not supported. See screenshot below:

![image](https://user-images.githubusercontent.com/99691/109429314-29b44700-79c9-11eb-85c2-e17a3e7c12cd.png)

**Comment by hmlendea** [comment]
Hello.

This is a known issue but unsolvable, since Electron does not support this kind of sign ins without UserAgent spoofing which we recently just removed due to it causing other issues.

So for the time being please use the classic login

**Comment by InfoSec812** [comment]
Thanks for the update... As far as I can tell, once you have enabled social login, there is no way to set a "classic" password. :(

**Comment by hmlendea** [comment]
I'm not sure if this will work for GeForce NOW but for other services, you can log in with a social button and then go the account settings and "change" the password

**Comment by InfoSec812** [comment]
I've been looking for an option to do that, but I cannot find it for GeForce NOW.
