### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by abasgames** [hmlendea/geforcenow-electron#41]
Trace/breakpoint trap

**Comment by hmlendea** [comment]
Hello,

Can you please elaborate a bit more?

What distro (Arch/Ubuntu/etc.), desktop environment (GNOME/KDE/etc.) and display server (X11/Wayland) do you have?

What package are you running exactly? Is it installed through a package manager, is it downloaded and ran manually from the Releases tab (if so, which file did you get?)?

And what is the console output when running the app?
