### ISSUE TITLE
The game is laggy while playing it

### ISSUE THREAD

**Issue by 15locraft** [hmlendea/geforcenow-electron#42]

**Comment by KronwarsCZ** [comment]
This may be an issue with your connection and/or chosen nvidia server.

**Comment by 3nuc** [comment]
The performance for me (in order from best to worst) was:
1. Windows desktop app
2. geforcenow-electron
3. playing from Chrome (it's officially available on all OSes now but back in the day you needed to fake the useragent as if you're playing from a Chromebook)

I assume the desktop app is doing some magic underneath?

**Comment by KronwarsCZ** [comment]
Yes. it appears that way. I also miss changing streaming settings to competitive.

**Comment by hmlendea** [comment]
Closing as there is already a thread for performance/lag issues ( #31 )

Also, the latest version of `geforcenow-electron` (v1.1.0) that I just released should solve those issues.
