### ISSUE TITLE
Launch Issues?

### ISSUE THREAD

**Issue by RadNuke** [hmlendea/geforcenow-electron#46]
I am running the Debian Distro Parrot OS on my laptop and I use this on my trip and I wanted to get GeForce now for it and as I was getting everything I needed and when I tried launching the app I ran into an issue, I made sure Chrome-Sandbox is set to Root Owner and on 4755. I'll add a screenshot of my Terminal window and my log. Thanks in advance for any help.
![Screenshot at 2021-04-12 13-32-44](https://user-images.githubusercontent.com/82404904/114436233-9d469800-9bb4-11eb-89ce-811431ab3ad5.png)
[2021-04-12T17_32_30_482Z-debug.log](https://github.com/hmlendea/geforcenow-electron/files/6298646/2021-04-12T17_32_30_482Z-debug.log)

**Comment by hmlendea** [comment]
Does the precompiled version run if you download it from the Releases tab?
