### ISSUE TITLE
Keyboard layout missing in settings

### ISSUE THREAD

**Issue by karpaz** [hmlendea/geforcenow-electron#48]
Hello, I have issue with this problem.

When I run GFNow from Ubuntntu, "GNOME Software" and choose flatpak version (1.0.8), than I can change layout in settings, but when I change app to snap (1.1.1) than I cannot change my keyboard layout. The option is missing in settings tab.

Both app is installed from "GNOME Software" I didn't tested deb variant, but I think, it will be same as snap version. 

I already search some info about that and find this. I hope that it will help.
https://www.nvidia.com/en-us/geforce/forums/discover/435830/keyboard-layout-missing-in-gfn-settings/

**Comment by hmlendea** [comment]
Hmmm... I thought that option was removed for everyone - as after I ran it through the official web version on Chrome, the option was still missing

Version 1.0.8 still has the ChromeOS UserAgent which would explain why the option is still available.

I will look to see what can be done about it and if there is any way to do it without changing the UserAgent.

In any case... if you have trouble with the default layout being incorrect (e.g. special characters are messed up / british, when entering passwords) you can work around it by pressing Alt+Shift which will switch the keyboard layout on the host Windows machine to something normal (US International I assume)

**Comment by foxy6520** [comment]
This issue is still pending.
