### ISSUE TITLE
Cannot Login with google Account

### ISSUE THREAD

**Issue by rienex** [hmlendea/geforcenow-electron#49]
Hi,
today I install new via snap and AppImage. Problem is, that I cannot login with google. After I enter my account name, message appears that the browser it not "safe" enough. 

Using Fedora and try AppImage and snap version 1.1.1

regards Tino

**Comment by hmlendea** [comment]
Hello

The problem is that Google intentionally blocks Electron apps for its services. Bypassing those restrictions is against the Google ToS and I'm reluctant to do it as it could endanger the users' accounts.

:(

**Comment by rienex** [comment]
Hello,

okay I unterstand. Thank you ver much!

I try the chrome version.. Maybee it works better in the meantime

https://play.geforcenow.com/

Kind regards

Tino

**Comment by hmlendea** [comment]
As I stated in #50 I will study the ToS to see if there's any way to have GAuth work without breaking the ToS and endangering end-users.
However it's not a high priority right now as not many users use GAuth with GFN, and there are more pressing issues to solve/implement currently.

**Comment by xor-128** [comment]
Implementing a redirect to real browser for google links is possible.

**Comment by watho** [comment]
What a wasting of time. Please add a notice to the readme to avoid unnecessary installs.

**Comment by JosTheDude** [comment]
It is possible to unlink from your google account and set a password in the NVIDIA Account Manager

[Account Manager](https://profile.nvgs.nvidia.com/security)

That's what I've done as an alternative fix

**Comment by roender** [comment]
> It is possible to unlink from your google account and set a password in the NVIDIA Account Manager
> 
> [Account Manager](https://profile.nvgs.nvidia.com/security)
> 
> That's what I've done as an alternative fix

Very good idea. It worked for me as well. Changing the password is crucial after unlinking accounts. After that you can simply use the e-mail (can still be google email address) and the new password to login. 2FA also worked after that for me. 

Thank you very much for the suggestion.

**Comment by jd-apprentice** [comment]
> It is possible to unlink from your google account and set a password in the NVIDIA Account Manager
> 
> [Account Manager](https://profile.nvgs.nvidia.com/security)
> 
> That's what I've done as an alternative fix

I may be stupid but.. Trying to add a password requests me for the actual one which I don't remember to setup one? since I've logged with google

Is there something that I'm missing out?
