### ISSUE TITLE
Problem with fullscreen

### ISSUE THREAD

**Issue by NicoRoumeau** [hmlendea/geforcenow-electron#56]
Hello, this is my first post in Github so very sorry if I make mistakes!

I installed geforce-electron on Fedora 34 via flathub.

The problem is that when I launch a game, Geforce propose me to enter in full screen by clicking "continue" (your server is ready - enter in fullscreen mode - continue), the full screen appears (behind), but the proposal remains. If I hit ESC, the proposal disapears but I'm not anymore in full screen. Am I clear? ;)

I made some screenshots.

![Capture d’écran du 2021-05-08 15-07-46](https://user-images.githubusercontent.com/83870710/117540718-bf470500-b010-11eb-916c-c2bda1522de5.png)

![Capture d’écran du 2021-05-08 15-08-20](https://user-images.githubusercontent.com/83870710/117540720-bfdf9b80-b010-11eb-9005-d81fd3e87a29.png)

![Capture d’écran du 2021-05-08 15-08-42](https://user-images.githubusercontent.com/83870710/117540721-bfdf9b80-b010-11eb-8af2-db091b3d9c57.png)

Thank you very much for this port.

**Comment by hmlendea** [comment]
Hello,

Please provide the following info:
 - Your distro
 - How did you install gfn-electron? (.deb, .appimage, package manager, etc)
 - Which version of gfn-electron are you using?

**Comment by NicoRoumeau** [comment]
Hello, thank you for your answer.

I'm on Fedora 34 (fresh install).
I install gfn-electron via Flathub website.
It's the 1.0.8 version.

**Comment by mburakov** [comment]
The ESC behavior might be related to #53.

@NicoRoumeau, are you on Gnome Wayland session by any chance?
Try switching to Gnome Xorg session, this might help.

**Comment by NicoRoumeau** [comment]
Thank you for your answer.

Yes I'm on Wayland. But I just opened an Xorg session and I got the same issue. In fact, GFN at the start is windowed, i select my game (play) and then a popup tells me that I've got to enter in Full Screen Mode, with a button "CONTINUE". When I click on this button, the full screen mode appears behind but the window telling me that I need to enter in full screen mode with the Continue button remains. And the only way to get disappear this window is to hit the ESC key, but I'm not anymore in full screen mode doing that!

**Comment by hmlendea** [comment]
The flatpak version is quite outdated. The latest release is 1.1.2.
Could you try downloading the latest version manually from the releases (the zip version for example) and running it from there and see if it works fine?

Also, Super(WinKey)+F should toggle between windowed and fullscreen, which could serve as a temporary "fix".

**Comment by hmlendea** [comment]
It is very weird that the issue still persists for you even with the latest version.

Is there any GNOME setting that you changed which you think could have interfered with the window arangements/tiling/focusing? Or an extension, maybe?

I also use GNOME but it's using X.org and it's on Arch - so it's not quite the same thing, but it works ok for me.

Regarding flat: I would, but I'm not really able to invest time into it and I have no prior knowledge to rely on :( I have opened an issue (#59) asking for volunteers, and hopefully someone will take it.

**Comment by hmlendea** [comment]
I've managed to figure out how to fix and update the FlatHub build myself. It's now using the latest version, yay!

**Comment by NicoRoumeau** [comment]
Thank you very much!!!

**Comment by nsrosenqvist** [comment]
I'm using the flathub flatpak as well and am also experiencing this issue (on X.org). What I had to do to solve it was to bind a keyboard shortcut to "toggle fullscren mode" in gnome-control-center, and when pressing it fullscreen is toggled off and the message disappears, then I'm able to toggle fullscreen back on again using the same keyboard shortcut. Maybe bind f11 for this to mimic the behavior for browsers so that a custom keyboard shortcut isn't required for those experiencing the issue?

**Comment by hmlendea** [comment]
> I'm using the flathub flatpak as well and am also experiencing this issue (on X.org). What I had to do to solve it was to bind a keyboard shortcut to "toggle fullscren mode" in gnome-control-center, and when pressing it fullscreen is toggled off and the message disappears, then I'm able to toggle fullscreen back on again using the same keyboard shortcut. Maybe bind f11 for this to mimic the behavior for browsers so that a custom keyboard shortcut isn't required for those experiencing the issue?

There's already a Super(WinKey)+F shortcut for toggling fullscreen, or is that not working in your case?

**Comment by vampywiz17** [comment]
Same problem, Fedora 34, Flatpak install, GNOME/x11

**Comment by Draecal** [comment]
### Same issue

* OS: _Pop OS_
* Updated: _Yes_
* Flatpack: _Yes_
* Version: _1.4.0_
