### ISSUE TITLE
Update the Flatpak version on FlatHub

### ISSUE THREAD

**Issue by hmlendea** [hmlendea/geforcenow-electron#59]
Hello,

I have no experience whatsoever with flatpaks / FlatHub, and it seems like the maintainer of the flatpak version of this app, hasn't updated it in quite a long time - it's still at v1.0.8, which has several issues that were fixed since then.

I am very tight on time and I would appreciate some help updating that version.

Preferably there would be someone who can take over as a maintainer of that version. But just helping me with info is very much appreciated also.

Thanks!

**Comment by hmlendea** [comment]
After battling with it for quite a while, I have managed to fix the flatpak build and upload it tot he latest version (1.1.3) myself :D

**Comment by nsrosenqvist** [comment]
This issue is relevant again, the flathub version is stuck at 1.1.3
