### ISSUE TITLE
Failed to load URL | FlatHub

### ISSUE THREAD

**Issue by Ethorbit** [hmlendea/geforcenow-electron#87]
When running:
`flatpak run io.github.hmlendea.geforcenow-electron`

I get:
 **electron: Failed to load URL: https://play.geforcenow.com/ with error: ERR_NAME_NOT_RESOLVED**

The Geforce NOW window opens, but it is blank.

> LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

**Comment by hmlendea** [comment]
Are you able to open that URL in a normal browser?
How does it behave when installing through the AUR? (non-flatpak)

**Comment by Ethorbit** [comment]
> Are you able to open that URL in a normal browser? How does it behave when installing through the AUR? (non-flatpak)

- I am able to open the URL in Chromium and Firefox.
- When installing from the AUR, the URL loads without any issues and I am able to see the GeForce NOW window like normal.

**Comment by hmlendea** [comment]
@Ethorbit what's the status in version 1.1.11?
