### ISSUE TITLE
Microphone icon permanently visible in-game even though it's unused. How to hide it?

### ISSUE THREAD

**Issue by Ishidres** [hmlendea/geforcenow-electron#89]
I play Cyberpunk 2077 using GeForce Now Electron. I don't use the microphone in-game but the microphone icon permanently appears at the top right of the game window (screenshot).

![Screenshot_1636394078](https://user-images.githubusercontent.com/17363426/140793224-693f89c9-d22a-4a2c-965e-4f306948baa2.png)

Is there a way to disable or remove this microphone icon?

Thanks.

**Comment by laurinneff** [comment]
Press Ctrl+M to disable the microphone

**Comment by Ishidres** [comment]
Thanks!
