### ISSUE TITLE
Publish packaged versions

### ISSUE THREAD

**Issue by JonathanTreffler** [hmlendea/geforcenow-electron#9]
Publishing for AppImage, Snap, Flatpack and deb would be great.

It should not be hard to do: https://www.electron.build/

I might create a Pull Request to implement this.

**Comment by hmlendea** [comment]
I was thinking of doing this, but the problem is that I have no way of testing whether it went packaged or not, since I only have access to Arch Linux and Windows.

If you could do it, it would be great.

**Comment by DylanRob** [comment]
ill try my best to do this.

**Comment by JonathanTreffler** [comment]
I created a Pull Request: #11
