### ISSUE TITLE
Empty screen after login

### ISSUE THREAD

**Issue by globeone** [hmlendea/geforcenow-electron#91]
Using the Snap version 1.1.10 on Ubuntu 20.04
The application starts
I can log in to Geforce Now 
Then it says close this tab to continue the only option is to close the window which leaves an blank window behind it. 

![2021-11-11 21-19-44_GeForceNowAfterLogin](https://user-images.githubusercontent.com/10052587/141363591-b994260d-c09b-4499-a35d-e1fa7e801ffa.png)

**Comment by globeone** [comment]
Here one can see that the login screen works as normal but the actual choose the game from your library screen is blank

![2021-11-11_21-29-18_GeForceNowAfterLogin](https://user-images.githubusercontent.com/10052587/141364666-ec0f5f5e-0b9e-4ac3-b640-dbce33805c6e.png)

**Comment by globeone** [comment]
Some more info to help debug:
Was attempting to play on a Surface tablet running Ubuntu 20.04, which give a blank screen after login.

On the gaming rig also Ubuntu 20.04 am able to log in and play using geforcenow-electron and everything works fine.

**Comment by Potemkinkuliss** [comment]
I can confirm this issue on 0.3.2 on Ubuntu 20.04.3. (Snap install)

**Comment by HiJackerRZ** [comment]
Same problem

**Comment by squalou** [comment]
Same thing on pop02 20.04 (which is based on ubuntu 20.04).

One "interesting" thing : on this computer, playing through chrome-based browsers does not work, I have to tweak the user agent string. No idea if it can be related somehow.
And even weirder : using an extension to tweak the user agent does not work either : I have to use developers tools / more tools / network conditions / untick 'use default agent' there and set chrome os user agent from there.
Any other attempt will fail.

**Comment by squalou** [comment]
same thing on archlinux

**Comment by IgorKvasn** [comment]
I tried it couple of hours back and it didn't work for me, either. I tried it once more right now and it works - I did no changes to the OS, GFN or anything else... so give it another try, maybe it was just some error on Geforce's side and they resolved it?

**Comment by Potemkinkuliss** [comment]
No change yet. I tried three times.

**Comment by PopsicleEXE** [comment]
i'm having this issue too

**Comment by squalou** [comment]
I've just had a success with electron 14 instead of electron 15

in package.json : 

```package.json
-        "electron": "^15.3.0",
+        "electron": "^14",
```

then npm install && npm start

**Comment by hmlendea** [comment]
I am still investigating it and am not really sure what is the true problem, or more to the point what actually should be done to fix this.

As a backup solution I might just downgrade Electron to a version that works.
It's a bit hard though since on the systems that I can test on, it works with the latest version also.

Is anyone else able to confirm whether electron 14 works?

**Comment by hmlendea** [comment]
Might also be worth trying to wipe "~/.config/GeForce NOW" and see if that works.
Note: Removing that will wipe your session (you'll have to log in again). Consider just renaming that folder to something else instead, so that you ca rename it back later if the problem persists.

**Comment by squalou** [comment]
(additional info : I can't seem to access the "change keyboard layout". From my experience, I had to untick "use default useragent" in developer tools and set chrome os to have access to it. Here, change the strong in main.js does not help. Just like using an extension in chrome does not help. I wonder if setting the user agent string still works, be it on electron or chrome)

**Comment by Potemkinkuliss** [comment]
I can confirm: Downgrade to Electron 14 did the trick. Thank you!

**Comment by squalou** [comment]
I managed to have it work with electron15 with this minimal  tweak in main.js 

```
diff --git a/scripts/main.js b/scripts/main.js
index d5c4090..f9d6cf7 100644
--- a/scripts/main.js
+++ b/scripts/main.js
@@ -11,6 +11,7 @@ function createWindow() {
     webPreferences: {
       preload: path.join(__dirname, "preload.js"),
       contextIsolation: false,
+      nativeWindowOpen: false
     },
   });

```
`nativeWindowOpen: true` is the new default in electron 15.

This needs to be confirmed by others (with wiping cache and logout first and all)

**Comment by hmlendea** [comment]
I am pushing @squalou 's change as a quickfix, which will hopefully fix it for everybody.
I am still unable to reproduce the empty screen in any way :(
