### ISSUE TITLE
resolution 3440px x 1440px

### ISSUE THREAD

**Issue by Tealk** [hmlendea/geforcenow-electron#92]
Hello,

I have a monitor that has a resolution of 3440px x 1440px. Unfortunately I can not set this in the settings, is this a restriction of geforce or an electron problem?

**Comment by hmlendea** [comment]
Hi.

This is a GeForce NOW limitation. The maximum streaming resolution allowed by Nvidia is 1080p.

**Comment by Tealk** [comment]
Ok I was just surprised that it is so blurry; clear right and left is then a black edge but still it should have hd quality?

**Comment by anthr76** [comment]
From what I understand using a chromebook user agent should bypass the resolution and framerate limitations since they're supported there?

**Comment by Tealk** [comment]
Is it now possible?

> A maximum of 3,840 × 2,160 pixels is offered, but not through a web browser.

https://nationworldnews.com/geforce-now-nvidia-now-offers-wqhd-and-120-fps-in-edge-and-chrome/
