### ISSUE TITLE
[BUG]Your brouser is not safe and cant login Nvidia Account

### ISSUE THREAD

**Issue by siraprem** [hmlendea/geforcenow-electron#97]
**Describe the bug**
When you try to login with your nvidia account, say is not possible because the browser is not safe, cant open other browser, just open like a "internal browser" of the program

**To Reproduce**
1.Click on login tab of the nvidia app
2.A internal browser open
3.Try to login with my email and password 
4.A red message below the password box appear say something like "this browser is not safe"

**Expected behavior**
Let me in into my Nvidia account

**Screenshots**
![image](https://user-images.githubusercontent.com/95549581/144726127-97030c09-6962-44a3-9441-4d095fae8a62.png)

**System information:**
 - OS: [Manjaro Linux]
 - Desktop Environment: [XFCE 4.16]
 - Installation method: [AUR]
 - Version: [1.1.11-1]

**Additional context**
The error is in spanish but say in simple words: my browser is not safe

**Comment by hmlendea** [comment]
Hello.

I see you closed this issue, so I guess this is not a problem for you anymore. I still tried reproducing it today and I couldn't on my end.

Can you let me know how the issue went away, or what fix did you apply (if any)? This might come in handy if the issue does come back in the future to anyone else.

**Comment by siraprem** [comment]
hi! i dont know what i did to solve it, because i do 3 solutions at the time

1.Reinstall my default browser (Brave)
2.Connect with other wifi 
3.Restart my computer

one can be the solution... or all the 3 steps... after this, the login go normal and i can play with a input lag just a bit more than normal.

if can be a plus info, I recently installed manjaro, just 1 day using it in that moment, so is a very fresh installation

**Comment by MadByteDE** [comment]
I have the same issue with google account login using the AUR version. With flatpak it worked but my controllers where not recognized.

**Comment by hmlendea** [comment]
@MadByteDE yeah, unfortunately Google is not allowing Google SSO to work in Electron apps. Workarounds such as this may or may not work reliably.
This has also been discussed in #50 #49 #69 #99 .

Google sign-on is considered as not working and as unfixable (due to Google's Terms of Service)

**Comment by lmbak** [comment]
Method in **edit 4** from @MadByteDE also worked for me today.
